
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jul 01 17:58:05 PDT 2010
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 3;
  public static final int IDENT = 10;
  public static final int NUMBER = 9;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int DIV = 5;
  public static final int ASSIGN = 6;
  public static final int error = 1;
  public static final int RPAREN = 8;
  public static final int MUL = 4;
  public static final int LPAREN = 7;
}

